# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "b5830ef0857b056c23608b0df3eedfca"
application_url = "https://edgesidecart.onrender.com"
embedded = true
name = "EdgeCart"

[access_scopes]
scopes = "read_products,write_products,read_discounts,read_publications"

[app_proxy]
url = "https://edgesidecart.onrender.com"
subpath = "edge-cart"
prefix = "apps"

[webhooks]
api_version = "2025-07"

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/uninstalled"
  topics = [ "app/uninstalled" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/scopes_update"
  topics = [ "app/scopes_update" ]

[auth]
redirect_urls = [
  "https://edgesidecart.onrender.com/auth/callback",
  "https://edgesidecart.onrender.com/auth/shopify/callback",
  "https://edgesidecart.onrender.com/api/auth"
]

[build]
automatically_update_urls_on_dev = false
